import * as type from "./types";

export const tree: type.TreesResponse = {
  httpStatus: "success",
  message: "나무 검색 성공",
  trees: [
    {
      id: 1,
      imageUrl: "주소!!",
      name: "쿠마수정나무",
      fruits: [
        {
          id: 1,
          writerId: 1,
          writerNickname: "내가누구게",
          content: "잘지내~",
          imageUrl: "http://이미지주소",
          createTime: "14:10",
        },
      ],
      fruitsCount: 1,
    },
  ],
};

export const admin: type.Admin = {
  httpStatus: "success",
  reportList: [
    {
      id: 1,
      reporterId: 2,
      content: "신고합니디",
      completed: true,
      contentType: "TREE",
      targetId: 1,
    },
    {
      id: 2,
      reporterId: 2,
      content: "신고!!!",
      completed: false,
      contentType: "TREE",
      targetId: 1,
    },
    {
      id: 3,
      reporterId: 2,
      content: "신고요!!!",
      completed: false,
      contentType: "TREE",
      targetId: 1,
    },
    {
      id: 3,
      reporterId: 2,
      content: "신고요!!!",
      completed: false,
      contentType: "TREE",
      targetId: 1,
    },
    {
      id: 3,
      reporterId: 2,
      content: "신고요!!!",
      completed: false,
      contentType: "TREE",
      targetId: 1,
    },
    {
      id: 3,
      reporterId: 2,
      content: "신고요!!!",
      completed: false,
      contentType: "TREE",
      targetId: 1,
    },
    {
      id: 3,
      reporterId: 2,
      content: "신고요!!!",
      completed: false,
      contentType: "TREE",
      targetId: 1,
    },
    {
      id: 3,
      reporterId: 2,
      content: "신고요!!!",
      completed: false,
      contentType: "TREE",
      targetId: 1,
    },
    {
      id: 3,
      reporterId: 2,
      content: "신고요!!!",
      completed: false,
      contentType: "TREE",
      targetId: 1,
    },
    {
      id: 3,
      reporterId: 2,
      content: "신고요!!!",
      completed: false,
      contentType: "TREE",
      targetId: 1,
    },
    {
      id: 3,
      reporterId: 2,
      content: "신고요!!!",
      completed: false,
      contentType: "TREE",
      targetId: 1,
    },
    {
      id: 3,
      reporterId: 2,
      content: "신고요!!!",
      completed: false,
      contentType: "TREE",
      targetId: 1,
    },
  ],
  message: "신고 접수 내역 조회 성공",
};
