import "./globals.css";
import type { Metadata } from "next";
// import { Inter } from 'next/font/google'
import localFont from "next/font/local";

// const inter = Inter({ subsets: ['latin'] })

const bitBit = localFont({
  src: "../public/font/DNFBitBitv2.ttf",
  variable: "--font-bitBit",
});

const nexonGothic = localFont({
  src: "../public/font/NEXON-Lv2-Gothic.ttf",
  variable: "--font-nexonGothic",
});

const nexonGothic_Light = localFont({
  src: "../public/font/NEXON-Lv2-Gothic-Light.ttf",
  variable: "--font-nexonGothic-Light",
});

const nexonGothic_Medium = localFont({
  src: "../public/font/NEXON-Lv2-Gothic-Medium.ttf",
  variable: "--font-nexonGothic-Medium",
});

const nexonGothic_Bold = localFont({
  src: "../public/font/NEXON-Lv2-Gothic-Bold.ttf",
  variable: "--font-nexonGothic-Bold",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${bitBit.variable} ${nexonGothic.variable} ${nexonGothic_Light.variable} ${nexonGothic_Medium.variable} ${nexonGothic_Bold.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
